package com.gabe.rpg.init;

import net.minecraft.client.Minecraft;
import net.minecraft.client.resources.model.ModelResourceLocation;
import net.minecraft.init.Blocks;
import net.minecraft.item.Item;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemArmor.ArmorMaterial;
import net.minecraft.item.ItemStack;
import net.minecraft.util.WeightedRandomChestContent;
import net.minecraftforge.common.ChestGenHooks;
import net.minecraftforge.common.util.EnumHelper;
import net.minecraftforge.fml.common.registry.GameRegistry;

import com.gabe.rpg.Reference;
import com.gabe.rpg.ServerRPGMod;
import com.gabe.rpg.items.ItemCopperPlant;
import com.gabe.rpg.items.ItemRPGArmor;
import com.gabe.rpg.items.ItemRPGAxe;
import com.gabe.rpg.items.ItemRPGHoe;
import com.gabe.rpg.items.ItemRPGPickaxe;
import com.gabe.rpg.items.ItemRPGShovel;
import com.gabe.rpg.items.ItemRPGSword;
import com.gabe.rpg.items.ItemRubyPlant;
import com.gabe.rpg.items.RPGITem;

public class RPGItems {
	
	/** FIRST RELEASE **/
	
	// Name, Harvest Level (0 hand, 3 Diamond), Durability, Mining Speed, Damage (sword adds 4), Enchantibility
	public static ToolMaterial RUBY = EnumHelper.addToolMaterial("RUBY", 3, 766, 7.0F, 5.0F, 30);
	public static ToolMaterial ORG = EnumHelper.addToolMaterial("ORG", 3, 6000, 15.0F, 15.0F, 50);
	public static ToolMaterial COPPER = EnumHelper.addToolMaterial("COPPER", 2, 500, 5.0F, 3.0F, 20);
	public static ToolMaterial AMETHYST = EnumHelper.addToolMaterial("AMETHYST", 3, 1000, 8.0F, 16.0F, 30);
	public static ToolMaterial FWOOD = EnumHelper.addToolMaterial("FWOOD", 1, 50, 1.0F, 1.0F, 20);
	public static ToolMaterial TIN = EnumHelper.addToolMaterial("TIN", 3, 550, 6.0F, 4.0F, 30);
	public static ToolMaterial BRONZE = EnumHelper.addToolMaterial("BRONZE", 3, 1100, 8.0F, 5.0F, 30);
	
	//Name, texture path for wrap around, durability, damage array, Enchantability
	public static ArmorMaterial RUBYA = EnumHelper.addArmorMaterial("RUBYA", "rpg:ruby", 50, new int[]{3, 8, 6, 7}, 30);
	public static ArmorMaterial ORGA = EnumHelper.addArmorMaterial("ORGA", "rpg:org", 100, new int[]{5, 10, 8, 50}, 50);
	public static ArmorMaterial COPPERA = EnumHelper.addArmorMaterial("COPPERA", "rpg:copper", 17, new int[]{2, 7, 5, 2}, 30);
	public static ArmorMaterial AMETHYSTA = EnumHelper.addArmorMaterial("AMETHYST", "rpg:amethyst", 60, new int[]{4, 9, 7, 8}, 30);
	public static ArmorMaterial WOOD = EnumHelper.addArmorMaterial("WOOD", "rpg:wood", 10, new int[]{2, 4, 3, 2}, 20);
	public static ArmorMaterial TINA = EnumHelper.addArmorMaterial("TINA", "rpg:tin", 27, new int[]{3, 8, 6, 3}, 40);
	public static ArmorMaterial BRONZEA = EnumHelper.addArmorMaterial("BRONZEA", "rpg:bronze", 42, new int[]{5, 10, 8, 9}, 40);
	public static Item Ruby;
	public static Item RubyHelmet;
	public static Item RubyChestplate;
	public static Item RubyLeggings;
	public static Item RubyBoots;
	public static Item RubyPickaxe;
	public static Item RubySpade;
	public static Item RubyHoe;
	public static Item RubyAxe;
	public static Item RubySword;
	public static Item Build;
	public static Item IBuild;
	public static Item Orgrinite;
	public static Item OrgHelmet;
	public static Item OrgChestplate;
	public static Item OrgLeggings;
	public static Item OrgBoots;
	public static Item OrgPickaxe;
	public static Item OrgSpade;
	public static Item OrgHoe;
	public static Item OrgAxe;
	public static Item OrgSword;
	public static Item Penny;
	public static Item Nickel;
	public static Item Dime;
	public static Item Quarter;
	public static Item DollarCoin;
	public static Item $1;
	public static Item $2;
	public static Item $5;
	public static Item $10;
	public static Item $20;
	public static Item $50;
	public static Item $100;
	public static Item $500;
	public static Item $1000;
	public static Item $100000;
	public static Item Copper;
	public static Item CopperPickaxe;
	public static Item CopperAxe;
	public static Item CopperSpade;
	public static Item CopperHoe;
	public static Item CopperSword;
	public static Item CopperHelmet;
	public static Item CopperChestplate;
	public static Item CopperLeggings;
	public static Item CopperBoots;
	public static Item Amethyst;
	public static Item AmethystPickaxe;
	public static Item AmethystAxe;
	public static Item AmethystSpade;
	public static Item AmethystHoe;
	public static Item AmethystSword;
	public static Item AmethystHelmet;
	public static Item AmethystChestplate;
	public static Item AmethystLeggings;
	public static Item AmethystBoots;
	public static Item WoodHelmet;
	public static Item WoodChestplate;
	public static Item WoodLeggings;
	public static Item WoodBoots;
	public static Item Tin;
	public static Item TinPickaxe;
	public static Item TinAxe;
	public static Item TinSpade;
	public static Item TinHoe;
	public static Item TinSword;
	public static Item TinHelmet;
	public static Item TinChestplate;
	public static Item TinLeggings;
	public static Item TinBoots;
	public static Item Bronze;
	public static Item BronzePickaxe;
	public static Item BronzeAxe;
	public static Item BronzeSpade;
	public static Item BronzeHoe;
	public static Item BronzeSword;
	public static Item BronzeHelmet;
	public static Item BronzeChestplate;
	public static Item BronzeLeggings;
	public static Item BronzeBoots;
    public static Item ItemRubyPlant;
    public static Item ItemCopperPlant;
//	public static Item cords;
	
	public static void init() {
		//FIRST RELEASE
		Ruby = new Item().setUnlocalizedName("Ruby").setCreativeTab(ServerRPGMod.tabRPG).setContainerItem(Ruby);;
		Build = new Item().setUnlocalizedName("Build").setCreativeTab(ServerRPGMod.tabRPG);
		IBuild = new Item().setUnlocalizedName("IBuild").setCreativeTab(ServerRPGMod.tabRPG);
		Orgrinite = new RPGITem(null).setUnlocalizedName("Orgrinite").setCreativeTab(ServerRPGMod.tabRPG);
		Penny = new Item().setUnlocalizedName("Penny").setCreativeTab(ServerRPGMod.tabMONEY);
		Nickel = new Item().setUnlocalizedName("Nickel").setCreativeTab(ServerRPGMod.tabMONEY);
		Dime = new Item().setUnlocalizedName("Dime").setCreativeTab(ServerRPGMod.tabMONEY);
		Quarter = new Item().setUnlocalizedName("Quarter").setCreativeTab(ServerRPGMod.tabMONEY);
		DollarCoin = new Item().setUnlocalizedName("DollarCoin").setCreativeTab(ServerRPGMod.tabMONEY);
		$1 = new Item().setUnlocalizedName("$1").setCreativeTab(ServerRPGMod.tabMONEY);
		$2 = new Item().setUnlocalizedName("$2").setCreativeTab(ServerRPGMod.tabMONEY);
		$5 = new Item().setUnlocalizedName("$5").setCreativeTab(ServerRPGMod.tabMONEY);
		$10 = new Item().setUnlocalizedName("$10").setCreativeTab(ServerRPGMod.tabMONEY);
		$20 = new Item().setUnlocalizedName("$20").setCreativeTab(ServerRPGMod.tabMONEY);
		$50 = new Item().setUnlocalizedName("$50").setCreativeTab(ServerRPGMod.tabMONEY);
		$100 = new Item().setUnlocalizedName("$100").setCreativeTab(ServerRPGMod.tabMONEY);
		$500 = new Item().setUnlocalizedName("$500").setCreativeTab(ServerRPGMod.tabMONEY);
		$1000 = new Item().setUnlocalizedName("$1000").setCreativeTab(ServerRPGMod.tabMONEY);
		$100000 = new Item().setUnlocalizedName("$100000").setCreativeTab(ServerRPGMod.tabMONEY);
		Copper = new Item().setUnlocalizedName("Copper").setCreativeTab(ServerRPGMod.tabRPG);
		Amethyst = new Item().setUnlocalizedName("Amethyst").setCreativeTab(ServerRPGMod.tabRPG);
		Tin = new Item().setUnlocalizedName("Tin").setCreativeTab(ServerRPGMod.tabRPG);
		Bronze = new Item().setUnlocalizedName("Bronze").setCreativeTab(ServerRPGMod.tabRPG);
		ItemRubyPlant = new ItemRubyPlant(RPGBlocks.RubyPlant, RPGBlocks.RubyBlock);
		ItemCopperPlant = new ItemCopperPlant(RPGBlocks.CopperPlant, RPGBlocks.CopperBlock);
		
		ChestGenHooks.getInfo(ChestGenHooks.MINESHAFT_CORRIDOR).addItem(new WeightedRandomChestContent(new ItemStack(RPGItems.Amethyst), 1, 5, 15));
		ChestGenHooks.getInfo(ChestGenHooks.MINESHAFT_CORRIDOR).addItem(new WeightedRandomChestContent(new ItemStack(RPGItems.Bronze), 1, 5, 50));
		ChestGenHooks.getInfo(ChestGenHooks.BONUS_CHEST).addItem(new WeightedRandomChestContent(new ItemStack(RPGItems.Amethyst), 1, 5, 1));
		ChestGenHooks.getInfo(ChestGenHooks.BONUS_CHEST).addItem(new WeightedRandomChestContent(new ItemStack(RPGItems.Bronze), 1, 5, 15));
		ChestGenHooks.getInfo(ChestGenHooks.BONUS_CHEST).addItem(new WeightedRandomChestContent(new ItemStack(RPGItems.$10), 1, 5, 200));
		ChestGenHooks.getInfo(ChestGenHooks.VILLAGE_BLACKSMITH).addItem(new WeightedRandomChestContent(new ItemStack(RPGItems.Bronze), 1, 5, 65));
		ChestGenHooks.getInfo(ChestGenHooks.DUNGEON_CHEST).addItem(new WeightedRandomChestContent(new ItemStack(RPGItems.$100000), 1, 1, 1));
		
		
//		cords = new ItemCord().setUnlocalizedName("cords").setCreativeTab(ServerRPGMod.tabRPG);
		
	}
	
	public static void register()
	{
		//FIRST RELEASE   
		GameRegistry.registerItem(Ruby, Ruby.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(RubyPickaxe = new ItemRPGPickaxe("RubyPickaxe", RUBY), "RubyPickaxe");
		GameRegistry.registerItem(RubyAxe = new ItemRPGAxe("RubyAxe", RUBY), "RubyAxe");
		GameRegistry.registerItem(RubySpade = new ItemRPGShovel("RubySpade", RUBY), "RubySpade");
		GameRegistry.registerItem(RubyHoe = new ItemRPGHoe("RubyHoe", RUBY), "RubyHoe");
		GameRegistry.registerItem(RubySword = new ItemRPGSword("RubySword", RUBY), "RubySword");
		GameRegistry.registerItem(RubyHelmet = new ItemRPGArmor("RubyHelmet", RUBYA, 1, 0), "RubyHelmet");
		GameRegistry.registerItem(RubyChestplate = new ItemRPGArmor("RubyChestplate", RUBYA, 1, 1), "RubyChestplate");
		GameRegistry.registerItem(RubyLeggings = new ItemRPGArmor("RubyLeggings", RUBYA, 2, 2), "RubyLeggings");
		GameRegistry.registerItem(RubyBoots = new ItemRPGArmor("RubyBoots", RUBYA, 1, 3), "RubyBoots");
		GameRegistry.registerItem(Build, Build.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(IBuild, IBuild.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(Orgrinite, Orgrinite.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(OrgPickaxe = new ItemRPGPickaxe("OrgPickaxe", ORG), "OrgPickaxe");
		GameRegistry.registerItem(OrgAxe = new ItemRPGAxe("OrgAxe", ORG), "OrgAxe");
		GameRegistry.registerItem(OrgSpade = new ItemRPGShovel("OrgSpade", ORG), "OrgSpade");
		GameRegistry.registerItem(OrgHoe = new ItemRPGHoe("OrgHoe", ORG), "OrgHoe");
		GameRegistry.registerItem(OrgSword = new ItemRPGSword("OrgSword", ORG), "OrgSword");
		GameRegistry.registerItem(OrgHelmet = new ItemRPGArmor("OrgHelmet", ORGA, 1, 0), "OrgHelmet");
		GameRegistry.registerItem(OrgChestplate = new ItemRPGArmor("OrgChestplate", ORGA, 1, 1), "OrgChestplate");
		GameRegistry.registerItem(OrgLeggings = new ItemRPGArmor("OrgLeggings", ORGA, 2, 2), "OrgLeggings");
		GameRegistry.registerItem(OrgBoots = new ItemRPGArmor("OrgBoots", ORGA, 1, 3), "OrgBoots");
		GameRegistry.registerItem(Penny, Penny.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(Nickel, Nickel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(Dime, Dime.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(Quarter, Quarter.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(DollarCoin, DollarCoin.getUnlocalizedName().substring(5));
		GameRegistry.registerItem($1, $1.getUnlocalizedName().substring(5));
		GameRegistry.registerItem($2, $2.getUnlocalizedName().substring(5));
		GameRegistry.registerItem($5, $5.getUnlocalizedName().substring(5));
		GameRegistry.registerItem($10, $10.getUnlocalizedName().substring(5));
		GameRegistry.registerItem($20, $20.getUnlocalizedName().substring(5));
		GameRegistry.registerItem($50, $50.getUnlocalizedName().substring(5));
		GameRegistry.registerItem($100, $100.getUnlocalizedName().substring(5));
		GameRegistry.registerItem($500, $500.getUnlocalizedName().substring(5));
		GameRegistry.registerItem($1000, $1000.getUnlocalizedName().substring(5));
		GameRegistry.registerItem($100000, $100000.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(Copper, Copper.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(CopperPickaxe = new ItemRPGPickaxe("CopperPickaxe", COPPER), "CopperPickaxe");
		GameRegistry.registerItem(CopperAxe = new ItemRPGAxe("CopperAxe", COPPER), "CopperAxe");
		GameRegistry.registerItem(CopperSpade = new ItemRPGShovel("CopperSpade", COPPER), "CopperSpade");
		GameRegistry.registerItem(CopperHoe = new ItemRPGHoe("CopperHoe", COPPER), "CopperHoe");
		GameRegistry.registerItem(CopperSword = new ItemRPGSword("CopperSword", COPPER), "CopperSword");
		GameRegistry.registerItem(CopperHelmet = new ItemRPGArmor("CopperHelmet", COPPERA, 1, 0), "CopperHelmet");
		GameRegistry.registerItem(CopperChestplate = new ItemRPGArmor("CopperChestplate", COPPERA, 1, 1), "CopperChestplate");
		GameRegistry.registerItem(CopperLeggings = new ItemRPGArmor("CopperLeggings", COPPERA, 2, 2), "CopperLeggings");
		GameRegistry.registerItem(CopperBoots = new ItemRPGArmor("CopperBoots", COPPERA, 1, 3), "CopperBoots");
		GameRegistry.registerItem(Amethyst, Amethyst.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(AmethystPickaxe = new ItemRPGPickaxe("AmethystPickaxe", AMETHYST), "AmethystPickaxe");
		GameRegistry.registerItem(AmethystAxe = new ItemRPGAxe("AmethystAxe", AMETHYST), "AmethystAxe");
		GameRegistry.registerItem(AmethystSpade = new ItemRPGShovel("AmethystSpade", AMETHYST), "AmethystSpade");
		GameRegistry.registerItem(AmethystHoe = new ItemRPGHoe("AmethystHoe", AMETHYST), "AmethystHoe");
		GameRegistry.registerItem(AmethystSword = new ItemRPGSword("AmethystSword", AMETHYST), "AmethystSword");
		GameRegistry.registerItem(AmethystHelmet = new ItemRPGArmor("AmethystHelmet", AMETHYSTA, 1, 0), "AmethystHelmet");
		GameRegistry.registerItem(AmethystChestplate = new ItemRPGArmor("AmethystChestplate", AMETHYSTA, 1, 1), "AmethystChestplate");
		GameRegistry.registerItem(AmethystLeggings = new ItemRPGArmor("AmethystLeggings", AMETHYSTA, 2, 2), "AmethystLeggings");
		GameRegistry.registerItem(AmethystBoots = new ItemRPGArmor("AmethystBoots", AMETHYSTA, 1, 3), "AmethystBoots");
		GameRegistry.registerItem(WoodHelmet = new ItemRPGArmor("WoodHelmet", WOOD, 1, 0), "WoodHelmet");
		GameRegistry.registerItem(WoodChestplate = new ItemRPGArmor("WoodChestplate", WOOD, 1, 1), "WoodChestplate");
		GameRegistry.registerItem(WoodLeggings = new ItemRPGArmor("WoodLeggings", WOOD, 2, 2), "WoodLeggings");
		GameRegistry.registerItem(WoodBoots = new ItemRPGArmor("WoodBoots", WOOD, 1, 3), "WoodBoots");
		GameRegistry.registerItem(Tin, Tin.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(TinPickaxe = new ItemRPGPickaxe("TinPickaxe", TIN), "TinPickaxe");
		GameRegistry.registerItem(TinAxe = new ItemRPGAxe("TinAxe", TIN), "TinAxe");
		GameRegistry.registerItem(TinSpade = new ItemRPGShovel("TinSpade", TIN), "TinSpade");
		GameRegistry.registerItem(TinHoe = new ItemRPGHoe("TinHoe", TIN), "TinHoe");
		GameRegistry.registerItem(TinSword = new ItemRPGSword("TinSword", TIN), "TinSword");
		GameRegistry.registerItem(TinHelmet = new ItemRPGArmor("TinHelmet", TINA, 1, 0), "TinHelmet");
		GameRegistry.registerItem(TinChestplate = new ItemRPGArmor("TinChestplate", TINA, 1, 1), "TinChestplate");
		GameRegistry.registerItem(TinLeggings = new ItemRPGArmor("TinLeggings", TINA, 2, 2), "TinLeggings");
		GameRegistry.registerItem(TinBoots = new ItemRPGArmor("TinBoots", TINA, 1, 3), "TinBoots");
		GameRegistry.registerItem(Bronze, Bronze.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(BronzePickaxe = new ItemRPGPickaxe("BronzePickaxe", BRONZE), "BronzePickaxe");
		GameRegistry.registerItem(BronzeAxe = new ItemRPGAxe("BronzeAxe", BRONZE), "BronzeAxe");
		GameRegistry.registerItem(BronzeSpade = new ItemRPGShovel("BronzeSpade", BRONZE), "BronzeSpade");
		GameRegistry.registerItem(BronzeHoe = new ItemRPGHoe("BronzeHoe", BRONZE), "BronzeHoe");
		GameRegistry.registerItem(BronzeSword = new ItemRPGSword("BronzeSword", BRONZE), "BronzeSword");
		GameRegistry.registerItem(BronzeHelmet = new ItemRPGArmor("BronzeHelmet", BRONZEA, 1, 0), "BronzeHelmet");
		GameRegistry.registerItem(BronzeChestplate = new ItemRPGArmor("BronzeChestplate", BRONZEA, 1, 1), "BronzeChestplate");
		GameRegistry.registerItem(BronzeLeggings = new ItemRPGArmor("BronzeLeggings", BRONZEA, 2, 2), "BronzeLeggings");
		GameRegistry.registerItem(BronzeBoots = new ItemRPGArmor("BronzeBoots", BRONZEA, 1, 3), "BronzeBoots");
//		GameRegistry.registerItem(cords, cords.getUnlocalizedName().substring(5));
	}
	
		
		public static void registerRenders()
		{
			//FIRST RELEASE
			registerRender(Ruby);
			registerRender(RubyPickaxe);
			registerRender(RubyAxe);
			registerRender(RubySpade);
			registerRender(RubyHoe);
			registerRender(RubySword);
			registerRender(RubyHelmet);
			registerRender(RubyChestplate);
			registerRender(RubyLeggings);
			registerRender(RubyBoots);
			registerRender(Build);
			registerRender(IBuild);
			registerRender(Orgrinite);
			registerRender(OrgPickaxe);
			registerRender(OrgSpade);
			registerRender(OrgAxe);
			registerRender(OrgHoe);
			registerRender(OrgSword);
			registerRender(OrgHelmet);
			registerRender(OrgChestplate);
			registerRender(OrgLeggings);
			registerRender(OrgBoots);
			registerRender(Penny);
			registerRender(Nickel);
			registerRender(Dime);
			registerRender(Quarter);
			registerRender(DollarCoin);
			registerRender($1);
			registerRender($2);
			registerRender($5);
			registerRender($10);
			registerRender($20);
			registerRender($50);
			registerRender($100);
			registerRender($500);
			registerRender($1000);
			registerRender($100000);
			registerRender(Copper);
			registerRender(CopperPickaxe);
			registerRender(CopperSpade);
			registerRender(CopperAxe);
			registerRender(CopperHoe);
			registerRender(CopperSword);
			registerRender(CopperHelmet);
			registerRender(CopperChestplate);
			registerRender(CopperLeggings);
			registerRender(CopperBoots);
			registerRender(Amethyst);
			registerRender(AmethystPickaxe);
			registerRender(AmethystSpade);
			registerRender(AmethystAxe);
			registerRender(AmethystHoe);
			registerRender(AmethystSword);
			registerRender(AmethystHelmet);
			registerRender(AmethystChestplate);
			registerRender(AmethystLeggings);
			registerRender(AmethystBoots);
			registerRender(WoodHelmet);
			registerRender(WoodChestplate);
			registerRender(WoodLeggings);
			registerRender(WoodBoots);
			registerRender(Tin);
			registerRender(TinPickaxe);
			registerRender(TinAxe);
			registerRender(TinSpade);
			registerRender(TinHoe);
			registerRender(TinSword);
			registerRender(TinHelmet);
			registerRender(TinChestplate);
			registerRender(TinLeggings);
			registerRender(TinBoots);
			registerRender(Bronze);
			registerRender(BronzePickaxe);
			registerRender(BronzeAxe);
			registerRender(BronzeSpade);
			registerRender(BronzeHoe);
			registerRender(BronzeSword);
			registerRender(BronzeHelmet);
			registerRender(BronzeChestplate);
			registerRender(BronzeLeggings);
			registerRender(BronzeBoots);
//			registerRender(cords);
	}
		public static void registerRender(Item item)
		{
			Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(item, 0, new ModelResourceLocation(Reference.MOD_ID + ":" + item.getUnlocalizedName().substring(5), "inventory"));
		}
	}
